name: VITA
options:
  bundleIdPrefix: com.abolilagad
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  VITAPackage:
    path: .

targets:
  VITA:
    type: application
    platform: iOS
    sources:
      - path: VITA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abolilagad.vita
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: VITA/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: VITA/VITA.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: SFX34PW93C
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: VITAPackage
        product: VITACore
      - package: VITAPackage
        product: VITADesignSystem
      - package: VITAPackage
        product: CausalityEngine
