name: VITA
options:
  bundleIdPrefix: com.aditya.vita
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "6.24.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    DEVELOPMENT_TEAM: U9GQY85ZBA
    CODE_SIGN_STYLE: Automatic

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

targets:
  # ──────────────── Libraries ────────────────

  VITACore:
    templates: [Framework]
    sources:
      - path: Sources/VITACore
    dependencies:
      - package: GRDB

  VITADesignSystem:
    templates: [Framework]
    sources:
      - path: Sources/VITADesignSystem
    dependencies:
      - target: VITACore

  HealthKitBridge:
    templates: [Framework]
    sources:
      - path: Sources/HealthKitBridge
    dependencies:
      - target: VITACore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        OTHER_LDFLAGS: ["-weak_framework", "HealthKit"]

  ConsumptionBridge:
    templates: [Framework]
    sources:
      - path: Sources/ConsumptionBridge
    dependencies:
      - target: VITACore

  IntentionalityTracker:
    templates: [Framework]
    sources:
      - path: Sources/IntentionalityTracker
        excludes:
          - DeviceActivityReportExtension.swift
    dependencies:
      - target: VITACore

  EnvironmentBridge:
    templates: [Framework]
    sources:
      - path: Sources/EnvironmentBridge
    dependencies:
      - target: VITACore

  CausalityEngine:
    templates: [Framework]
    sources:
      - path: Sources/CausalityEngine
    dependencies:
      - target: VITACore

  # ──────────────── iOS App ────────────────

  VITA:
    type: application
    platform: iOS
    sources:
      - path: VITA
        excludes:
          - App/Info.plist
          - VITA.entitlements
    info:
      path: VITA/App/Info.plist
      properties:
        CFBundleName: VITA
        CFBundleDisplayName: VITA
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSHealthShareUsageDescription: "VITA needs access to your health data to analyze correlations between your meals, sleep, heart rate variability, and glucose levels. All data is processed locally on your device."
        NSHealthUpdateUsageDescription: "VITA may write health insights back to HealthKit for your reference."
        NSLocationWhenInUseUsageDescription: "VITA uses your location to fetch local weather, AQI, and pollen conditions for accurate health context."
        NSLocalNetworkUsageDescription: "VITA connects to your local backend server during development to sync delivery and grocery events."
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - processing
        VITABackendURL: "http://127.0.0.1:8000"
        VITAMockRotimaticEnabled: true
        VITAMockInstantPotEnabled: true
    entitlements:
      path: VITA/VITA.entitlements
      properties:
        com.apple.developer.healthkit: true
    dependencies:
      - target: VITACore
      - target: VITADesignSystem
      - target: HealthKitBridge
      - target: ConsumptionBridge
      - target: IntentionalityTracker
      - target: EnvironmentBridge
      - target: CausalityEngine
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aditya.vita
        INFOPLIST_FILE: VITA/App/Info.plist
