name: VITA
options:
  bundleIdPrefix: com.abolilagad
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  VITAPackage:
    path: .

targets:
  VITA:
    type: application
    platform: iOS
    sources:
      - path: VITA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abolilagad.vita
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: VITA/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: VITA/VITA.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: SFX34PW93C
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: VITAPackage
        product: VITACore
      - package: VITAPackage
        product: VITADesignSystem
      - package: VITAPackage
        product: HealthKitBridge
      - package: VITAPackage
        product: ConsumptionBridge
      - package: VITAPackage
        product: IntentionalityTracker
      - package: VITAPackage
        product: EnvironmentBridge
      - package: VITAPackage
        product: CausalityEngine
      - sdk: HealthKit.framework
      - target: WatchVITA
        embed: true

  WatchVITA:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: WatchVITA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abolilagad.vita.watchkitapp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.abolilagad.vita
        INFOPLIST_KEY_WKWatchOnly: NO
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: SFX34PW93C
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: VITAPackage
        product: VITACore
      - sdk: WatchConnectivity.framework
